name: tekartik_firebase_firestore_sembast
description: Firebase firestore sembast
version: 0.9.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sembast: '>=3.5.0+1'
  sembast_web: '>=2.0.0-3'
  uuid: '>=1.0.0'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=0.8.2'
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart3a
    version: '>=0.3.7'
  path:
dev_dependencies:
  test: any
  dev_test:
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  tekartik_firebase_firestore_test:
    path: ../firestore_test
  process_run: '>=0.10.8'
  build_web_compilers: ">=2.0.0"
dependency_overrides:
  tekartik_firebase_firestore:
    path: ../firestore
