name: tekartik_firebase_firestore_sim
description: Firebase simulation
version: 0.8.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_firebase_sim:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_sim
      ref: dart2_3
    version: '>=0.3.7'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart2_3
    version: '>=0.8.0'
  meta: any
  synchronized: '>=1.5.0-dev.2'
  logging: any
  path:
  json_rpc_2:
dev_dependencies:
  test: "^1.0.0"
  dev_test: '>=0.12.0-dev.1'
  build_runner: ">=0.9.1"
  build_web_compilers: ">=0.4.0+4"
  build_test: ">=0.10.3"
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_firebase_firestore:
    path: ../firestore