name: tekartik_firebase_firestore_sim
description: Firebase simulation
version: 0.8.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  tekartik_firebase_sim:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase_sim
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=0.8.0'
  meta: ">=1.15.0"
  synchronized: '>=1.5.0-dev.2'
  logging: any
  path: ">=1.9.0"
  json_rpc_2:
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  build_test: ">=0.10.3"
  process_run: ">=1.2.1+1"

resolution: workspace
