name: tekartik_firebase_firestore_test
description: Firebase firestore test
version: 0.8.2
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.3.9+1'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=0.8.0'
  dev_test: ">=1.0.0"
  path:
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_dev_menu
dev_dependencies:
  dev_build: '>=0.12.0-dev.1'
  process_run: '>=0.10.2'

resolution: workspace
