name: tekartik_firebase_firestore_test
description: Firebase firestore test
version: 0.8.2
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: null_safety
    version: '>=0.3.9+1'
  tekartik_firebase_firestore:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: null_safety
    version: '>=0.8.0'
  test: ">=1.0.0"

dev_dependencies:
  dev_test: '>=0.12.0-dev.1'
  process_run: '>=0.10.2'

dependency_overrides:
  tekartik_firebase_firestore:
    path: ../firestore