name: tekartik_firebase_firestore_test
description: Firebase firestore test
version: 0.8.2
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.3.9+1'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=0.8.0'
  dev_test: ">=1.0.0+4"
  path: ">=1.9.0"
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_dev_menu
dev_dependencies:
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"

resolution: workspace
